---
# eg. [ssh_user]@[ssh_host]:[ssh_port]
ssh_uri: root@127.0.0.1:22
ssh_identity: 
ssh_tunnels:
# 监听端口: nc -lp 4444  查看端口: netstat -anp
# R: 反向隧道, L: 正向隧道, D: ss代理, H: 原地http代理, S:原地ss代理
# - R=>0.0.0.0:13141=>localhost:3389
# - L=>0.0.0.0:12345=>localhost:22
# - D=>0.0.0.0:11080
# - H=>0.0.0.0:3128



