---
ssh_uri: jenkins@moyi-lc.com:49183
ssh_user: jenkins
ssh_host: moyi-lc.com
ssh_port: 49183
ssh_identity: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
  QyNTUxOQAAACATQwMkiaCP7I4nOFvBPomMZJT+1PTyLnkwyHuaXJWDMQAAAKArmOrvK5jq
  7wAAAAtzc2gtZWQyNTUxOQAAACATQwMkiaCP7I4nOFvBPomMZJT+1PTyLnkwyHuaXJWDMQ
  AAAEAfpUur6iMOKhzxRc4TiWkKCBXLLSuY3JU+V4PLyiYGrxNDAySJoI/sjic4W8E+iYxk
  lP7U9PIueTDIe5pclYMxAAAAFnlvdXJfZW1haWxAZXhhbXBsZS5jb20BAgMEBQYH
  -----END OPENSSH PRIVATE KEY-----
ssh_passwd:
ssh_tunnels:
   # 监听端口: nc -lp 4444  查看端口: netstat -anp
   # ssh -NTR 0.0.0.0:3389:localhost:3389 jenkins@moyi-lc.com
   - R=>0.0.0.0:3389=>localhost:3389
---
